package embed

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNewLines(t *testing.T) {
	assert := assert.New(t)
	in := "// Code generated by \"esc\"; DO NOT EDIT.\r\n\r\npackage main\r\n\r\nimport"
	expect := "// Code generated by \"esc\"; DO NOT EDIT.\n\npackage main\n\nimport"
	assert.Equal(expect, replaceNewLines(in))
}
